"""Deleted column is_logged_in

Revision ID: 740b4c9a16fd
Revises: 
Create Date: 2022-04-20 20:40:09.302250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740b4c9a16fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Login', schema=None) as batch_op:
        batch_op.drop_column('is_logged_in')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_logged_in', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
