"""Added column what_he_is_doing

Revision ID: e65f4bc10a06
Revises: 9ce42e904194
Create Date: 2022-04-20 20:46:07.269263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65f4bc10a06'
down_revision = '9ce42e904194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('what_he_is_doing', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Login', schema=None) as batch_op:
        batch_op.drop_column('what_he_is_doing')

    # ### end Alembic commands ###
